#!/usr/bin/env bash

function links(){
  file="$1"

  $SED -i 's|#changelog.asciidoc#changelog_changelog)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#credentials.asciidoc#credentials_credentials_endpoint)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#credentials.asciidoc#credentials_credentials_object)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#credentials.asciidoc#credentials_credentials_role_class)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#credentials.asciidoc#credentials_registration)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#credentials_credentials_role_class)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#credentials_delete_method)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#credentials_get_method)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#credentials_post_method)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#credentials_put_method)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#mod_cdrs.asciidoc#mod_cdrs_cdr_object)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#mod_cdrs.asciidoc#mod_cdrs_cdrs_module)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#mod_charging_profiles.asciidoc#mod_charging_profiles_module)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#mod_commands.asciidoc#mod_commands_cancelreservation_object)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#mod_commands.asciidoc#mod_commands_commands_module)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#mod_commands.asciidoc#mod_commands_reservenow_object)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#mod_commands.asciidoc#mod_commands_startsession_object)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#mod_commands.asciidoc#mod_commands_stopsession_object)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#mod_commands.asciidoc#mod_commands_unlockconnector_object)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#mod_hub_client_info.asciidoc#mod_hub_client_info_module)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#mod_locations.asciidoc#mod_locations_businessdetails_class)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#mod_locations.asciidoc#mod_locations_location_object)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#mod_locations.asciidoc#mod_locations_locations_module)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#mod_locations_connector_object)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#mod_locations_emsp_interface)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#mod_locations_energysource_class)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#mod_locations_environmentalimpact_class)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#mod_locations_evse_object)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#mod_locations_get_list_request_parameters)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#mod_locations_get_method)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#mod_locations_get_method_eMSP)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#mod_locations_get_object_request_parameters)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#mod_locations_location_object)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#mod_locations_patch_method)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#mod_locations_publish_token_class)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#mod_locations_put_method)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#mod_sessions.asciidoc#mod_sessions_session_object)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#mod_sessions.asciidoc#mod_sessions_sessions_module)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#mod_sessions.asciidoc#mod_sessions_set_charging_preferences)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#mod_tariffs.asciidoc#mod_tariffs_tariff_object)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#mod_tariffs.asciidoc#mod_tariffs_tariffs_module)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#mod_tokens.asciidoc#mod_tokens_token_object)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#mod_tokens.asciidoc#mod_tokens_tokens_module)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#status_codes.asciidoc#status_codes_3xxx_server_errors)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#status_codes.asciidoc#status_codes_status_codes)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#terminology.asciidoc#terminology_roles)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#transport_and_format.asciidoc#transport_and_format_authorization_header)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#transport_and_format.asciidoc#transport_and_format_client_owned_object_push)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#transport_and_format.asciidoc#transport_and_format_message_routing)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#transport_and_format.asciidoc#transport_and_format_message_routing_broadcast_push)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#transport_and_format.asciidoc#transport_and_format_message_routing_open_routing_request)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#transport_and_format.asciidoc#transport_and_format_paginated_request)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#transport_and_format.asciidoc#transport_and_format_paginated_response)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#transport_and_format.asciidoc#transport_and_format_pagination)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#transport_and_format_get)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#transport_and_format_get_all_via_hubs)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#transport_and_format_message_routing_broadcast_push)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#transport_and_format_message_routing_open_routing_request)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#transport_and_format_patch)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#transport_and_format_pull_and_push)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#transport_and_format_put)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#types.asciidoc#types_cistring_type)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#types.asciidoc#types_datetime_type)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#types.asciidoc#types_role_enum)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#types.asciidoc#types_string_type)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#types.asciidoc#types_url_type)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#version_information_endpoint.asciidoc#versions_module)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#version_information_endpoint_endpoint_class)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#version_information_endpoint_interface_role_enum)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#version_information_endpoint_moduleid_enum)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#version_information_endpoint_version_class)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#version_information_endpoint_version_details_endpoint)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#version_information_endpoint_version_information_endpoint)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#version_information_endpoint_versionnumber_enum)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#mod_locations_energysourcecategory_enum)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#types.asciidoc#types_number_type)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#mod_locations_environmentalimpactcategory_enum)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#types.asciidoc#types_number_type)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#mod_locations_regularhours_class)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#mod_locations_exceptionalperiod_class)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#mod_locations_imagecategory_enum)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#mod_tokens_tokentype_enum)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#mod_locations_status_enum)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#mod_locations_flow_and_lifecycle)|https://ocpi.dev)|g' "$file"
  # $SED -i 's|)|https://ocpi.dev)|g' "$file"
  # $SED -i 's|)|https://ocpi.dev)|g' "$file"
  # $SED -i 's|)|https://ocpi.dev)|g' "$file"
  # $SED -i 's|)|https://ocpi.dev)|g' "$file"
  # $SED -i 's|)|https://ocpi.dev)|g' "$file"
  # $SED -i 's|)|https://ocpi.dev)|g' "$file"
}
