#!/usr/bin/env bash

function links(){
  file="$1"

  $SED -i 's|#changelog.asciidoc#changelog_changelog)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#credentials.asciidoc#credentials_credentials_endpoint)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#credentials.asciidoc#credentials_credentials_role_class)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#mod_cdrs.asciidoc#mod_cdrs_cdr_object)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#mod_cdrs.asciidoc#mod_cdrs_cdrs_module)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#mod_charging_profiles.asciidoc#mod_charging_profiles_module)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#mod_commands.asciidoc#mod_commands_cancelreservation_object)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#mod_commands.asciidoc#mod_commands_commands_module)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#mod_hub_client_info.asciidoc#mod_hub_client_info_module)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#mod_locations.asciidoc#mod_locations_location_object)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#mod_locations.asciidoc#mod_locations_locations_module)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#mod_sessions.asciidoc#mod_sessions_session_object)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#mod_sessions.asciidoc#mod_sessions_sessions_module)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#mod_sessions.asciidoc#mod_sessions_set_charging_preferences)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#mod_tariffs.asciidoc#mod_tariffs_tariff_object)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#mod_tariffs.asciidoc#mod_tariffs_tariffs_module)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#mod_tokens.asciidoc#mod_tokens_token_object)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#mod_tokens.asciidoc#mod_tokens_tokens_module)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#transport_and_format.asciidoc#transport_and_format_client_owned_object_push)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#transport_and_format.asciidoc#transport_and_format_message_routing)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#transport_and_format.asciidoc#transport_and_format_message_routing_broadcast_push)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#transport_and_format.asciidoc#transport_and_format_message_routing_open_routing_request)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#types.asciidoc#types_role_enum)|https://ocpi.dev)|g' "$file"
  $SED -i 's|#version_information_endpoint.asciidoc#versions_module)|https://ocpi.dev)|g' "$file"
  # $SED -i 's|)|https://ocpi.dev)|g' "$file"
  # $SED -i 's|)|https://ocpi.dev)|g' "$file"
  # $SED -i 's|)|https://ocpi.dev)|g' "$file"
  # $SED -i 's|)|https://ocpi.dev)|g' "$file"
  # $SED -i 's|)|https://ocpi.dev)|g' "$file"
  # $SED -i 's|)|https://ocpi.dev)|g' "$file"
  # $SED -i 's|)|https://ocpi.dev)|g' "$file"
  # $SED -i 's|)|https://ocpi.dev)|g' "$file"
  # $SED -i 's|)|https://ocpi.dev)|g' "$file"
  # $SED -i 's|)|https://ocpi.dev)|g' "$file"
  # $SED -i 's|)|https://ocpi.dev)|g' "$file"
  # $SED -i 's|)|https://ocpi.dev)|g' "$file"
  # $SED -i 's|)|https://ocpi.dev)|g' "$file"
  # $SED -i 's|)|https://ocpi.dev)|g' "$file"
  # $SED -i 's|)|https://ocpi.dev)|g' "$file"
  # $SED -i 's|)|https://ocpi.dev)|g' "$file"
  # $SED -i 's|)|https://ocpi.dev)|g' "$file"
  # $SED -i 's|)|https://ocpi.dev)|g' "$file"
  # $SED -i 's|)|https://ocpi.dev)|g' "$file"
  # $SED -i 's|)|https://ocpi.dev)|g' "$file"
  # $SED -i 's|)|https://ocpi.dev)|g' "$file"
  # $SED -i 's|)|https://ocpi.dev)|g' "$file"
  # $SED -i 's|)|https://ocpi.dev)|g' "$file"
  # $SED -i 's|)|https://ocpi.dev)|g' "$file"
  # $SED -i 's|)|https://ocpi.dev)|g' "$file"
  # $SED -i 's|)|https://ocpi.dev)|g' "$file"
  # $SED -i 's|)|https://ocpi.dev)|g' "$file"
  # $SED -i 's|)|https://ocpi.dev)|g' "$file"
  # $SED -i 's|)|https://ocpi.dev)|g' "$file"
  # $SED -i 's|)|https://ocpi.dev)|g' "$file"
  # $SED -i 's|)|https://ocpi.dev)|g' "$file"
  # $SED -i 's|)|https://ocpi.dev)|g' "$file"
  # $SED -i 's|(credentials.md#credentials-object)|(https://ocpi.dev)|g' "$file"
  # $SED -i 's|(credentials.md)|(https://ocpi.dev)|g' "$file"
  # $SED -i 's|(mod_cdrs.md)|(https://ocpi.dev)|g' "$file"
  # $SED -i 's|(mod_locations.md)|(https://ocpi.dev)|g' "$file"
  # $SED -i 's|(mod_sessions.md)|(https://ocpi.dev)|g' "$file"
  # $SED -i 's|(mod_tariffs.md)|(https://ocpi.dev)|g' "$file"
  # $SED -i 's|(mod_tokens.md)|(https://ocpi.dev)|g' "$file"
  # $SED -i 's|(status_codes.md#status-codes)|(https://ocpi.dev)|g' "$file"
  # $SED -i 's|(types.md#12_datetime_type)|(https://ocpi.dev)|g' "$file"
  # $SED -i 's|(types.md#13_decimal_type)|(https://ocpi.dev)|g' "$file"
  # $SED -i 's|(types.md#14_url)|(https://ocpi.dev)|g' "$file"
  # $SED -i 's|(types.md#14_url_type)|(https://ocpi.dev)|g' "$file"
  # $SED -i 's|changelog.asciidoc#changelog_changelog|https://ocpi.dev|g' "$file"


  # $SED -i 's|<<changelog.asciidoc#changelog_changelog,changelog>>|https://ocpi.dev[Changelog]|g' "$file"
  # $SED -i 's|<<credentials.asciidoc#credentials_credentials_role_class,Support Platforms with multiple/different roles, additional roles>>|https://ocpi.dev[Support Platforms with multiple/different roles, additional roles]|g' "$file"
  # $SED -i 's|<<mod_cdrs.asciidoc#mod_cdrs_cdr_object,CDRs>>|https://ocpi.dev[CDRs]|g' "$file"
  # $SED -i 's|<<mod_charging_profiles.asciidoc#mod_charging_profiles_module,Charging Profiles>>|https://ocpi.dev[Charging Profiles]|g' "$file"
  # $SED -i 's|<<mod_commands.asciidoc#mod_commands_cancelreservation_object,Commands>>|https://ocpi.dev[Commands]|g' "$file"
  # $SED -i 's|<<mod_hub_client_info.asciidoc#mod_hub_client_info_module,Hub Client Info>>|https://ocpi.dev[Hub Client Info]|g' "$file"
  # $SED -i 's|<<mod_locations.asciidoc#mod_locations_location_object,Locations>>|https://ocpi.dev[Locations]|g' "$file"
  # $SED -i 's|<<mod_sessions.asciidoc#mod_sessions_session_object,Sessions>>|https://ocpi.dev[Sessions]|g' "$file"
  # $SED -i 's|<<mod_sessions.asciidoc#mod_sessions_set_charging_preferences,Preference based Smart Charging>>|https://ocpi.dev[Preference based Smart Charging]|g' "$file"
  # $SED -i 's|<<mod_tariffs.asciidoc#mod_tariffs_tariff_object,Tariffs>>|https://ocpi.dev[Tariffs]|g' "$file"
  # $SED -i 's|<<mod_tokens.asciidoc#mod_tokens_token_object,Tokens>>|https://ocpi.dev[Tokens]|g' "$file"
  # $SED -i 's|<<transport_and_format.asciidoc#transport_and_format_message_routing,Message routing headers>>|https://ocpi.dev[Message routing headers]|g' "$file"

  # $SED -i 's|<<types.asciidoc#types_role_enum,CPO>>|https://ocpi.dev[CPO]|g' "$file"
  # $SED -i 's|<<types.asciidoc#types_role_enum,eMSP>>|https://ocpi.dev[eMSP]|g' "$file"
  # $SED -i 's|<<types.asciidoc#types_role_enum,Hub>>|https://ocpi.dev[Hub]|g' "$file"
  # $SED -i 's|<<types.asciidoc#types_role_enum,NSP>>|https://ocpi.dev[NSP]|g' "$file"
  # $SED -i 's|<<types.asciidoc#types_role_enum,NAP>>|https://ocpi.dev[NAP]|g' "$file"
  # $SED -i 's|<<types.asciidoc#types_role_enum,SCSP>>|https://ocpi.dev[SCSP]|g' "$file"
  # $SED -i 's|<<mod_cdrs.asciidoc#mod_cdrs_cdrs_module,CDRs>>|https://ocpi.dev[CDRs]|g' "$file"
  # $SED -i 's|<<mod_commands.asciidoc#mod_commands_commands_module,Commands>>|https://ocpi.dev[Commands]|g' "$file"
  # $SED -i 's|<<credentials.asciidoc#credentials_credentials_endpoint,Credentials>>|https://ocpi.dev[Credentials]|g' "$file"
  # $SED -i 's|<<mod_locations.asciidoc#mod_locations_locations_module,Locations>>|https://ocpi.dev[Locations]|g' "$file"
  # $SED -i 's|<<mod_sessions.asciidoc#mod_sessions_sessions_module,Sessions>>|https://ocpi.dev[Sessions]|g' "$file"
  # $SED -i 's|<<mod_tariffs.asciidoc#mod_tariffs_tariffs_module,Tariffs>>|https://ocpi.dev[Tariffs]|g' "$file"
  # $SED -i 's|<<mod_tokens.asciidoc#mod_tokens_tokens_module,Tokens>>|https://ocpi.dev[Tokens]|g' "$file"
  # $SED -i 's|<<version_information_endpoint.asciidoc#versions_module,Versions>>|https://ocpi.dev[Versions]|g' "$file"
  # $SED -i 's||https://ocpi.dev[]|g' "$file"
  # $SED -i 's||https://ocpi.dev[]|g' "$file"
  # $SED -i 's||https://ocpi.dev[]|g' "$file"
  # $SED -i 's||https://ocpi.dev[]|g' "$file"
  # $SED -i 's||https://ocpi.dev[]|g' "$file"
  # $SED -i 's||https://ocpi.dev[]|g' "$file"
  # $SED -i 's||https://ocpi.dev[]|g' "$file"
  # $SED -i 's||https://ocpi.dev[]|g' "$file"
  # $SED -i 's||https://ocpi.dev[]|g' "$file"
  # $SED -i 's||https://ocpi.dev[]|g' "$file"
  # $SED -i 's||https://ocpi.dev[]|g' "$file"
  # $SED -i 's||https://ocpi.dev[]|g' "$file"
  # $SED -i 's||https://ocpi.dev[]|g' "$file"
}
