#!/usr/bin/env bash

function replace(){
  target="$1"
  replacement="$2"
  file="$3"
  gsed -i "s|$target|$replacement|g" "$file"
}



function links(){
  file="$1"

  gsed -i 's|(#changelog.asciidoc#changelog_changelog)|(https://ocpi.dev)|g' "$file"

  replace "(#credentials.asciidoc#credentials_credentials_endpoint)"    "(/06-modules/02-credentials/01-intro.md)"                                    "$file"
  replace "(#credentials.asciidoc#credentials_credentials_object)"      "(/06-modules/02-credentials/06-object-description.md#credentials-object)"    "$file"
  replace "(#credentials.asciidoc#credentials_credentials_role_class)"  "(/06-modules/02-credentials/07-data-types.md#credentialsrole-class)"         "$file"
  replace "(#credentials.asciidoc#credentials_registration)"            "(/06-modules/02-credentials/03-use-cases.md#registration)"                   "$file"
  replace "(#credentials_credentials_role_class)"                       "(/06-modules/02-credentials/07-data-types.md#credentialsrole-class)"         "$file"
  replace "(#credentials_delete_method)"                                "(/06-modules/02-credentials/05-interfaces-and-endpoints.md#delete-method)"   "$file"
  replace "(#credentials_get_method)"                                   "(/06-modules/02-credentials/05-interfaces-and-endpoints.md#get-method)"      "$file"
  replace "(#credentials_post_method)"                                  "(/06-modules/02-credentials/05-interfaces-and-endpoints.md#post-method)"     "$file"
  replace "(#credentials_put_method)"                                   "(/06-modules/02-credentials/05-interfaces-and-endpoints.md#put-method)"      "$file"
  
  replace "(#mod_cdrs.asciidoc#mod_cdrs_authmethod_enum)"      "(/06-modules/05-cdrs/07-data-types.md#authmethod-enum)"             "$file"
  replace "(#mod_cdrs.asciidoc#mod_cdrs_cdr_object)"           "(/06-modules/05-cdrs/06-object-description.md#cdr-object)"          "$file"
  replace "(#mod_cdrs.asciidoc#mod_cdrs_cdr_token_object)"     "(/06-modules/05-cdrs/07-data-types.md#cdrtoken-class)"              "$file"
  replace "(#mod_cdrs.asciidoc#mod_cdrs_cdrs_module)"          "(/06-modules/05-cdrs/01-intro.md)"                                  "$file"
  replace "(#mod_cdrs.asciidoc#mod_cdrs_chargingperiod_class)" "(/06-modules/05-cdrs/07-data-types.md#chargingperiod-class)"        "$file"
  replace "(#mod_cdrs.asciidoc#mod_cdrs_step_size)"            "(/06-modules/05-cdrs/06-object-description.md#step_size)"           "$file"
  replace "(#mod_cdrs_authmethod_enum)"                        "(/06-modules/05-cdrs/07-data-types.md#authmethod-enum)"             "$file"
  replace "(#mod_cdrs_cdr_location_class)"                     "(/06-modules/05-cdrs/07-data-types.md#cdrlocation-class)"           "$file"
  replace "(#mod_cdrs_cdr_object)"                             "(/06-modules/05-cdrs/06-object-description.md#cdr-object)"          "$file"
  replace "(#mod_cdrs_cdr_token_object)"                       "(/06-modules/05-cdrs/07-data-types.md#cdrtoken-class)"              "$file"
  replace "(#mod_cdrs_cdrdimension_class)"                     "(/06-modules/05-cdrs/07-data-types.md#cdrdimension-class)"          "$file"
  replace "(#mod_cdrs_cdrdimensiontype_enum)"                  "(/06-modules/05-cdrs/07-data-types.md#cdrdimensiontype-enum)"       "$file"
  replace "(#mod_cdrs_chargingperiod_class)"                   "(/06-modules/05-cdrs/07-data-types.md#chargingperiod-class)"        "$file"
  replace "(#mod_cdrs_cpo_get_method)"                         "(/06-modules/05-cdrs/05-interfaces-and-endpoints.md#get-method)"    "$file"
  replace "(#mod_cdrs_credit_cdrs)"                            "(/06-modules/05-cdrs/04-flow-and-lifecycle.md#credit-cdrs)"         "$file"
  replace "(#mod_cdrs_msp_get_method)"                         "(/06-modules/05-cdrs/05-interfaces-and-endpoints.md#get-method-1)"  "$file"
  replace "(#mod_cdrs_post_method)"                            "(/06-modules/05-cdrs/05-interfaces-and-endpoints.md#post-method)"   "$file"
  replace "(#mod_cdrs_signed_data_class)"                      "(/06-modules/05-cdrs/07-data-types.md#signeddata-class)"            "$file"
  replace "(#mod_cdrs_signed_value_class)"                     "(/06-modules/05-cdrs/07-data-types.md#signedvalue-class)"           "$file"

  replace "(#mod_charging_profiles.asciidoc#mod_charging_profiles_module)"  "(/06-modules/09-charging-profiles/01-intro.md)"                                              "$file"
  replace "(#mod_charging_profiles_active_charging_profile_class)"          "(/06-modules/09-charging-profiles/07-data-types.md#activechargingprofile-class)"             "$file"
  replace "(#mod_charging_profiles_active_charging_profiles_result_object)" "(/06-modules/09-charging-profiles/06-object-description.md#chargingprofileresult-object)"    "$file"
  replace "(#mod_charging_profiles_charging_profile_class)"                 "(/06-modules/09-charging-profiles/07-data-types.md#chargingprofile-class)"                   "$file"
  replace "(#mod_charging_profiles_charging_profile_period_class)"          "(/06-modules/09-charging-profiles/07-data-types.md#chargingprofileperiod-class)"             "$file"
  replace "(#mod_charging_profiles_charging_profiles_result_object)"        "(/06-modules/09-charging-profiles/06-object-description.md#chargingprofileresult-object)"    "$file"
  replace "(#mod_charging_profiles_chargingrateunit)"                       "(/06-modules/09-charging-profiles/07-data-types.md#chargingrateunit-enum)"                   "$file"
  replace "(#mod_charging_profiles_clear_profiles_result_object)"           "(/06-modules/09-charging-profiles/06-object-description.md#clearprofileresult-object)"       "$file"
  replace "(#mod_charging_profiles_cpo_delete_method)"                      "(/06-modules/09-charging-profiles/05-interfaces-and-endpoints.md#delete-method)"             "$file"
  replace "(#mod_charging_profiles_cpo_get_method)"                         "(/06-modules/09-charging-profiles/05-interfaces-and-endpoints.md#get-method)"                "$file"
  replace "(#mod_charging_profiles_cpo_put_method)"                         "(/06-modules/09-charging-profiles/05-interfaces-and-endpoints.md#put-method)"                "$file"
  replace "(#mod_charging_profiles_msp_post_method)"                        "(/06-modules/09-charging-profiles/05-interfaces-and-endpoints.md#post-method)"               "$file"
  replace "(#mod_charging_profiles_msp_put_method)"                         "(/06-modules/09-charging-profiles/05-interfaces-and-endpoints.md#put-method-1)"              "$file"
  replace "(#mod_charging_profiles_response_object)"                        "(/06-modules/09-charging-profiles/06-object-description.md#chargingprofileresponse-object)"  "$file"
  replace "(#mod_charging_profiles_responsetype_enum)"                      "(/06-modules/09-charging-profiles/07-data-types.md#chargingprofileresponsetype-enum)"        "$file"
  replace "(#mod_charging_profiles_resulttype_enum)"                        "(/06-modules/09-charging-profiles/07-data-types.md#chargingprofileresulttype-enum)"          "$file"
  replace "(#mod_charging_profiles_set_charging_profile_object)"            "(/06-modules/09-charging-profiles/06-object-description.md#setchargingprofile-object)"       "$file"

  replace "(#mod_commands.asciidoc#mod_commands_cancelreservation_object)" "(/06-modules/08-commands/06-object-description.md#cancelreservation-object)" "$file"
  replace "(#mod_commands.asciidoc#mod_commands_commands_module)"          "(/06-modules/08-commands/01-intro.md)"                                       "$file"
  replace "(#mod_commands.asciidoc#mod_commands_reservenow_object)"        "(/06-modules/08-commands/06-object-description.md#reservenow-object)"        "$file"
  replace "(#mod_commands.asciidoc#mod_commands_startsession_object)"      "(/06-modules/08-commands/06-object-description.md#startsession-object)"      "$file"
  replace "(#mod_commands.asciidoc#mod_commands_stopsession_object)"       "(/06-modules/08-commands/06-object-description.md#stopsession-object)"       "$file"
  replace "(#mod_commands.asciidoc#mod_commands_unlockconnector_object)"   "(/06-modules/08-commands/06-object-description.md#unlockconnector-object)"   "$file"
  replace "(#mod_commands_cancelreservation_object)"                       "(/06-modules/08-commands/06-object-description.md#cancelreservation-object)" "$file"
  replace "(#mod_commands_commandresponse_object)"                         "(/06-modules/08-commands/06-object-description.md#commandresponse-object)"   "$file"
  replace "(#mod_commands_commandresponsetype_enum)"                       "(/06-modules/08-commands/07-data-types.md#commandresponsetype-enum)"         "$file"
  replace "(#mod_commands_commandresult_object)"                           "(/06-modules/08-commands/06-object-description.md#commandresult-object)"     "$file"
  replace "(#mod_commands_commandresulttype_enum)"                         "(/06-modules/08-commands/07-data-types.md#commandresulttype-enum)"           "$file"
  replace "(#mod_commands_commandtype_enum)"                               "(/06-modules/08-commands/07-data-types.md#commandtype-enum)"                 "$file"
  replace "(#mod_commands_cpo_post_method)"                                "(/06-modules/08-commands/05-interfaces-and-endpoints.md#post-method)"        "$file"
  replace "(#mod_commands_msp_post_method)"                                "(/06-modules/08-commands/05-interfaces-and-endpoints.md#post-method-1)"      "$file"
  replace "(#mod_commands_reservenow_object)"                              "(/06-modules/08-commands/06-object-description.md#reservenow-object)"        "$file"
  replace "(#mod_commands_startsession_object)"                            "(/06-modules/08-commands/06-object-description.md#startsession-object)"      "$file"
  replace "(#mod_commands_stopsession_object)"                             "(/06-modules/08-commands/06-object-description.md#stopsession-object)"       "$file"
  replace "(#mod_commands_unlockconnector_object)"                         "(/06-modules/08-commands/06-object-description.md#unlockconnector-object)"   "$file"

  gsed -i 's|(#mod_hub_client_info.asciidoc#mod_hub_client_info_module)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_hub_client_info_client_get)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_hub_client_info_client_put)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_hub_client_info_hub_client_info_object)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_hub_client_info_hub_connection_type_enum)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_hub_client_info_hub_get)|(https://ocpi.dev)|g' "$file"
  
  gsed -i 's|(#mod_locations.asciidoc#mod_locations_businessdetails_class)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_locations.asciidoc#mod_locations_capability_enum)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_locations.asciidoc#mod_locations_connector_object)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_locations.asciidoc#mod_locations_connectorformat_enum)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_locations.asciidoc#mod_locations_connectortype_enum)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_locations.asciidoc#mod_locations_energymix_class)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_locations.asciidoc#mod_locations_evse_object)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_locations.asciidoc#mod_locations_geolocation_class)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_locations.asciidoc#mod_locations_location_object)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_locations.asciidoc#mod_locations_locations_module)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_locations.asciidoc#mod_locations_powertype_enum)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_locations.asciidoc)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_locations_additionalgeolocation_class)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_locations_businessdetails_class)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_locations_capability_enum)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_locations_connector_object)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_locations_connectorformat_enum)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_locations_connectortype_enum)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_locations_emsp_interface)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_locations_energymix_class)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_locations_energysource_class)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_locations_energysourcecategory_enum)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_locations_environmentalimpact_class)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_locations_environmentalimpactcategory_enum)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_locations_evse_object)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_locations_exceptionalperiod_class)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_locations_facility_enum)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_locations_flow_and_lifecycle)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_locations_geolocation_class)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_locations_get_list_request_parameters)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_locations_get_method)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_locations_get_method_eMSP)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_locations_get_object_request_parameters)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_locations_hours_class)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_locations_image_class)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_locations_imagecategory_enum)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_locations_location_object)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_locations_locations_module)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_locations_parkingrestriction_enum)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_locations_parkingtype_enum)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_locations_patch_method)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_locations_powertype_enum)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_locations_publish_token_class)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_locations_put_method)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_locations_regularhours_class)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_locations_status_enum)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_locations_statusschedule_class)|(https://ocpi.dev)|g' "$file"
  
  gsed -i 's|(#mod_sessions.asciidoc#mod_sessions_profile_type_enum)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_sessions.asciidoc#mod_sessions_session_object)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_sessions.asciidoc#mod_sessions_sessions_module)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_sessions.asciidoc#mod_sessions_set_charging_preferences)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_sessions_charging_preferences_object)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_sessions_charging_preferences_response_enum)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_sessions_cpo_get_method)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_sessions_cpo_put_method)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_sessions_msp_get_method)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_sessions_msp_put_method)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_sessions_patch_method)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_sessions_profile_type_enum)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_sessions_session_object)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_sessions_sessionstatus_enum)|(https://ocpi.dev)|g' "$file"
  
  gsed -i 's|(#mod_tariffs.asciidoc#mod_tariffs_pricecomponent_class)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_tariffs.asciidoc#mod_tariffs_tariff_object)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_tariffs.asciidoc#mod_tariffs_tariffdimensiontype_enum)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_tariffs.asciidoc#mod_tariffs_tariffelement_class)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_tariffs.asciidoc#mod_tariffs_tariffs_module)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_tariffs_cpo_get_method)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_tariffs_dayofweek_enum)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_tariffs_delete_method)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_tariffs_free_of_charge_tariff_example)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_tariffs_msp_get_method)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_tariffs_msp_get_method)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_tariffs_pricecomponent_class)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_tariffs_put_method)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_tariffs_reservation_restriction_type)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_tariffs_tariff_example_15_reservation_5_euro_per_hour)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_tariffs_tariff_object)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_tariffs_tariff_type)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_tariffs_tariffdimensiontype_enum)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_tariffs_tariffelement_class)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_tariffs_tariffrestrictions_class)|(https://ocpi.dev)|g' "$file"
  
  gsed -i 's|(#mod_tokens.asciidoc#mod_tokens_energy_contract)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_tokens.asciidoc#mod_tokens_real-time_authorization)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_tokens.asciidoc#mod_tokens_token_object)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_tokens.asciidoc#mod_tokens_tokens_module)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_tokens.asciidoc#mod_tokens_tokentype_enum)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_tokens_allowed_enum)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_tokens_authorizationinfo_object)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_tokens_cpo_get_method)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_tokens_locationreferences_class)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_tokens_msp_get_method)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_tokens_patch_method)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_tokens_post_method)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_tokens_put_method)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_tokens_real-time_authorization)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_tokens_token_object)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_tokens_tokentype_enum)|(https://ocpi.dev)|g' "$file"
  gsed -i 's|(#mod_tokens_whitelisttype_enum)|(https://ocpi.dev)|g' "$file"
  
  gsed -i 's|(#status_codes.asciidoc#status_codes_2xxx_client_errors)|(/05-status-codes/05-status-codes.md#2xxx-client-errors)|g' "$file"
  gsed -i 's|(#status_codes.asciidoc#status_codes_3xxx_server_errors)|(/05-status-codes/05-status-codes.md#3xxx-server-errors)|g' "$file"
  gsed -i 's|(#status_codes.asciidoc#status_codes_status_codes)|(/05-status-codes/05-status-codes.md)|g' "$file"
  
  gsed -i 's|(#terminology.asciidoc#terminology_roles)|(/02-terminology-and-definitions/03-ev-charging-market-roles.md)|g' "$file"
  
  gsed -i 's|(#transport_and_format.asciidoc#transport_and_format_authorization_header)|(/04-transport-and-format/01-json-http-implementation-guide.md#authorization-header)|g' "$file"
  gsed -i 's|(#transport_and_format.asciidoc#transport_and_format_client_owned_object_push)|(/04-transport-and-format/01-json-http-implementation-guide.md#client-owned-object-push)|g' "$file"
  gsed -i 's|(#transport_and_format.asciidoc#transport_and_format_message_routing)|(/04-transport-and-format/01-json-http-implementation-guide.md#message-routing)|g' "$file"
  gsed -i 's|(#transport_and_format.asciidoc#transport_and_format_message_routing_broadcast_push)|(/04-transport-and-format/01-json-http-implementation-guide.md#broadcast-push)|g' "$file"
  gsed -i 's|(#transport_and_format.asciidoc#transport_and_format_message_routing_open_routing_request)|(/04-transport-and-format/01-json-http-implementation-guide.md#open-routing-request)|g' "$file"
  gsed -i 's|(#transport_and_format.asciidoc#transport_and_format_not_available)|(/04-transport-and-format/01-json-http-implementation-guide.md#no-data-available)|g' "$file"
  gsed -i 's|(#transport_and_format.asciidoc#transport_and_format_paginated_request)|(/04-transport-and-format/01-json-http-implementation-guide.md#paginated-request)|g' "$file"
  gsed -i 's|(#transport_and_format.asciidoc#transport_and_format_paginated_response)|(/04-transport-and-format/01-json-http-implementation-guide.md#paginated-response)|g' "$file"
  gsed -i 's|(#transport_and_format.asciidoc#transport_and_format_pagination)|(/04-transport-and-format/01-json-http-implementation-guide.md#pagination)|g' "$file"
  gsed -i 's|(#transport_and_format.asciidoc#transport_and_format_response_format)|(/04-transport-and-format/01-json-http-implementation-guide.md#response-format)|g' "$file"
  gsed -i 's|(#transport_and_format_get)|(#get-method)|g' "$file"
  gsed -i 's|(#transport_and_format_get_all_via_hubs)|(#get-all-via-hubs)|g' "$file" 
  gsed -i 's|(#transport_and_format_message_routing_broadcast_push)|(#broadcast-push)|g' "$file"
  gsed -i 's|(#transport_and_format_message_routing_open_routing_request)|(#open-routing-request)|g' "$file"
  gsed -i 's|(#transport_and_format_patch)|(#patch-method)|g' "$file"
  gsed -i 's|(#transport_and_format_pull_and_push)|(#pull-and-push)|g' "$file"
  gsed -i 's|(#transport_and_format_put)|(#put-method)|g' "$file"
  gsed -i 's|(#transport_and_format_response_format)|(#response-format)|g' "$file"
  
  gsed -i 's|(#types.asciidoc#types_cistring_type)|(/07-types/01-intro.md#cistring-type)|g' "$file"
  gsed -i 's|(#types.asciidoc#types_datetime_type)|(/07-types/01-intro.md#datetime-type)|g' "$file"
  gsed -i 's|(#types.asciidoc#types_displaytext_class)|(/07-types/01-intro.md#displaytext-class)|g' "$file"
  gsed -i 's|(#types.asciidoc#types_number_type)|(/07-types/01-intro.md#number-type)|g' "$file"
  gsed -i 's|(#types.asciidoc#types_price_class)|(/07-types/01-intro.md#price-class)|g' "$file"
  gsed -i 's|(#types.asciidoc#types_role_enum)|(/07-types/01-intro.md#role-enum)|g' "$file"
  gsed -i 's|(#types.asciidoc#types_string_type)|(/07-types/01-intro.md#string-type)|g' "$file"
  gsed -i 's|(#types.asciidoc#types_url_type)|(/07-types/01-intro.md#url-type)|g' "$file"
  gsed -i 's|(#types_number_type)|(#number-type)|g' "$file"
  gsed -i 's|(#types_string_type)|(#string-type)|g' "$file"
  
  gsed -i 's|(#version_information_endpoint.asciidoc#versions_module)|(/06-modules/01-versions/01-intro.md)|g' "$file"
  gsed -i 's|(#version_information_endpoint_endpoint_class)|(/06-modules/01-versions/03-details-endpoint.md#endpoint-class)|g' "$file"
  gsed -i 's|(#version_information_endpoint_interface_role_enum)|(/06-modules/01-versions/03-details-endpoint.md#interfacerole-enum)|g' "$file"
  gsed -i 's|(#version_information_endpoint_moduleid_enum)|(/06-modules/01-versions/03-details-endpoint.md#moduleid-enum)|g' "$file"
  gsed -i 's|(#version_information_endpoint_version_class)|(/06-modules/01-versions/02-information-endpoint.md#version-class)|g' "$file"
  gsed -i 's|(#version_information_endpoint_version_details_endpoint)|(/06-modules/01-versions/03-details-endpoint.md)|g' "$file"
  gsed -i 's|(#version_information_endpoint_version_information_endpoint)|(/06-modules/01-versions/02-information-endpoint.md)|g' "$file"
  gsed -i 's|(#version_information_endpoint_versionnumber_enum)|(/06-modules/01-versions/03-details-endpoint.md#versionnumber-enum)|g' "$file"

}
